### ISSUE TITLE
Submit package to MELPA?

### ISSUE THREAD

**Issue by dakrone** [ryuslash/eshell-fringe-status#1]
It would be great if this package were on Melpa, is there any interest in submitting it?

**Comment by ryuslash** [comment]
Hi,

Thanks for the suggestion, I've been thinking about doing that for a while, guess I'll finally have to do it now.

**Comment by ryuslash** [comment]
See melpa/melpa#3949

**Comment by dakrone** [comment]
Thanks! I'll follow the other issue :)
