### ISSUE TITLE
Fringe status removes first character at the start of the prompt line

### ISSUE THREAD

**Issue by mallt** [ryuslash/eshell-fringe-status#3]
When activating the fringe status mode, the first character at the start of the prompt line seems to be removed (the screenshot shows eshell before and after activating the fringe mode):

<img width="363" alt="screenshot-fringe-mode" src="https://user-images.githubusercontent.com/8885691/28971779-8af424cc-792d-11e7-98f4-1a3c23bccf36.png">

Do you have an idea how this could be fixed? Thanks!

**Comment by ryuslash** [comment]
Hey, I know this has been an extremely long time to wait, but I've just run a few simple tests and I can't reproduce the error. What is the value of your `eshell-prompt-function` and `eshell-prompt-regexp`?

**Comment by mallt** [comment]
This is my `eshell-prompt-function`:
``` elisp
(setq eshell-prompt-function
      (lambda ()
        (concat (when (file-remote-p default-directory)
                  (concat (file-remote-p default-directory 'user)
                          "@"
                          (file-remote-p default-directory 'host)
                          "\n"))
                (abbreviate-file-name (eshell/pwd))
                "\n $ ")))
```

The `eshell-prompt-regexp` is set to the default value `"^[^#$\n]* [#$] "`.

Thanks!

**Comment by ryuslash** [comment]
Running with `emacs -Q`, setting your variables and enabling `eshell-fringe-status-mode` still doesn't produce this result. Have you tried reproducing this using `emacs -Q`?

**Comment by mallt** [comment]
Thank you for checking! I'm sorry indeed, in `emacs -Q` the problem doesn't occur. I will check my config. Thanks again!
